apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-10-03T15:35:46Z"
    generateName: objects-7774b5c7cf-
    generation: 1
    labels:
      app: objects
      pod-template-hash: 7774b5c7cf
    name: objects-7774b5c7cf-kdmn2
    namespace: bd-g06
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: objects-7774b5c7cf
      uid: 13f64439-d5b8-4ac2-b51a-0d2e477224a7
    resourceVersion: "7934"
    uid: 38ef3661-5f03-452e-9b39-493965ef70b9
  spec:
    automountServiceAccountToken: false
    containers:
    - args:
      - mini
      - -dir=/data
      - -s3.config=/auth/s3.json
      command:
      - weed
      image: chrislusf/seaweedfs@sha256:4e61d15fd35994cb1e43e1e553dff106794841fd9a99ade2fc8c8bfce4d7872d
      imagePullPolicy: IfNotPresent
      name: store
      ports:
      - containerPort: 8333
        name: s3
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 3
        successThreshold: 1
        tcpSocket:
          port: s3
        timeoutSeconds: 1
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /data
        name: data
      - mountPath: /auth
        name: auth
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: desktop-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: object-data
    - name: auth
      secret:
        defaultMode: 420
        secretName: s3-config
  status:
    allocatedResources:
      cpu: 500m
      memory: 512Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T15:35:50Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T15:35:50Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T15:36:05Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T15:36:05Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-10-03T15:35:50Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 500m
        memory: 512Mi
      containerID: containerd://0e78b2bd2136a39a1c25b133f5b19d15f9a1060b0579abb70d0a2cd5aaf7231b
      image: sha256:7b5ca1f11aa4c91593612d2d4a9e253ec9152a4bd13a19e551290a042a4c52f5
      imageID: docker.io/chrislusf/seaweedfs@sha256:4e61d15fd35994cb1e43e1e553dff106794841fd9a99ade2fc8c8bfce4d7872d
      lastState: {}
      name: store
      ready: true
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-10-03T15:35:59Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
          uid: 1000
      volumeMounts:
      - mountPath: /data
        name: data
      - mountPath: /auth
        name: auth
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.18.0.4
    hostIPs:
    - ip: 172.18.0.4
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.6
    podIPs:
    - ip: 10.244.0.6
    qosClass: Burstable
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 489m
        memory: 512Mi
    startTime: "2026-10-03T15:35:50Z"
kind: List
metadata:
  resourceVersion: ""
