apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"name":"team-budget","namespace":"bd-g06"},"spec":{"hard":{"limits.cpu":"4","limits.memory":"4Gi","persistentvolumeclaims":"2","pods":"10","requests.cpu":"2","requests.memory":"2Gi","requests.storage":"8Gi"}}}
  creationTimestamp: "2026-10-01T08:31:03Z"
  name: team-budget
  namespace: bd-g06
  resourceVersion: "1336"
  uid: a3c9636d-6059-4c6e-874f-8a10c20083ff
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "2"
    pods: "10"
    requests.cpu: "2"
    requests.memory: 2Gi
    requests.storage: 8Gi
status:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "2"
    pods: "10"
    requests.cpu: "2"
    requests.memory: 2Gi
    requests.storage: 8Gi
  used:
    limits.cpu: 200m
    limits.memory: 256Mi
    persistentvolumeclaims: "0"
    pods: "1"
    requests.cpu: 100m
    requests.memory: 128Mi
    requests.storage: "0"
